=== makramibrahim/CS213/public_html/week08/BSA.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--bsa has one or more child-->
<!ELEMENT bsa (council+)>

<!--council has one or more element troops-->
<!ELEMENT council (troop+)>

<!--troop element has two attributes; number and unit name-->
<!ELEMENT troop (scout+)>

<!-- all elements in scout listed here--> 
<!ELEMENT scout (firstName, lastName, address, phoneNumber, rank*, meritbadge*)>

<!--strat first row-->
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>

<!-- list all the child address here -->
<!ELEMENT address (street, city, state)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!--end address-->

<!--get phone number element-->
<!ELEMENT phoneNumber (#PCDATA)>

<!--Declare for element rank-->
<!ELEMENT rank EMPTY>

<!--Declare for element meritbadge-->
<!ELEMENT meritbadge EMPTY>

<!ATTLIST council name CDATA #REQUIRED>
<!ATTLIST troop number CDATA #REQUIRED>
<!ATTLIST troop unitName CDATA #REQUIRED>

<!--The rank element has a required date-earned attribute-->
<!ATTLIST rank dateEarned CDATA #REQUIRED>
<!ATTLIST rank content (Eagle|2ndClass|1stClass|Star|Life|Tenderfoot) #IMPLIED>
<!--The meritbadge element has a required date-earned attribute-->
<!ATTLIST meritbadge dateEarned CDATA #REQUIRED>
<!ATTLIST meritbadge content CDATA #IMPLIED>

=== makramibrahim/CS213/public_html/week08/BSA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bsa SYSTEM "BSA.dtd">

<bsa> <!--root tree-->
	<council name="parents"> <!--the parents for troop and scout-->
		<troop number="2" unitName="child"> <!--child council-->

			<!-- all elements in scout listed here--> 
			<scout>
				<firstName>Alberto</firstName>
				<lastName>Razo</lastName>

				<!-- list all the child address here -->
				<address>
					<street>35 Center St</street>
					<city>Provo</city>
					<state>Utah</state>
				</address>

				<!--get phone number element-->
			 	<phoneNumber>333-444-9999</phoneNumber>
			 	<!--The rank element has a required date-earned attribute-->

			 	<rank dateEarned="12/12/2012" content="Eagle"/>
			 	<!--The meritbadge element has a required date-earned attribute-->
			 	<meritbadge dateEarned="11/11/2011" content="First Aid"/>
			</scout>
		</troop>
	</council>
</bsa>
